### ISSUE TITLE
Add MFA functionality for fetching value from `:result` 

### ISSUE THREAD

**Issue by leggebroten** [marcdel/open_telemetry_decorator#103]
the `:result` functionality is largely useless as return values are rarely simple primitives.  

Typically, the return value is a tuple and "pathing" isn't sufficient.  

I'd like to submit a PR that extends the pathing feature I mention in [issue 102](https://github.com/marcdel/open_telemetry_decorator/issues/102).

It would allow the client to provide a function in the `:include` path to more flexibly fetch the desired value

**Comment by marcdel** [comment]
I definitely see the issue, but I'm not convinced it's worth taking on that complexity. There are lots of cases where you'll need/want to use `Tracer.set_attribute` for things that aren't easily representable in the `include`, and I don't think providing a function in the decorator would be easier or more ergonomic.

I think if we `inspect` the result when it's a tuple, that's probably a reasonable enough default behavior.
