### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by epinault** [marcdel/open_telemetry_decorator#105]
so it would be nice to have a changelog. I see you use releases but changelog are likely much better as tools like dependabot can use them.

I cannot find any details about 1.3.x in changelog or release to make sure it won t break anything . any details?

**Comment by marcdel** [comment]
Yeah, fair point. I'm not in the habit of writing changelogs, but I'm happy to start. Let me look into what tooling is available to make sure that gets done as I cut new versions.

As for your specific question about 1.3, there is a breaking (kind of) change. The API hasn't changed at all, but it will no longer overwrite function input parameters in the span attributes if they are rebound in the body of the function.

e.g. this `param_override(3, 2)` will add `x=3` to the span, where previously it would have been `x=4`

```
@decorate trace("param_override", include: [:x, :y])
def param_override(x, y) do
  x = x + 1

  {:ok, x + y}
end
```

**Comment by marcdel** [comment]
We have a changelog!
https://github.com/marcdel/open_telemetry_decorator/blob/main/CHANGELOG.md

![image](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjEzMWFiNTFjNmFmYTMyZTQzMGMyZDVjMDVkMjQ5YjRiZGM5OTM2YSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/cEYFeDB8PpXqYekMuPK/giphy.gif)
