### ISSUE TITLE
Feature request, ability to add a link to the created span

### ISSUE THREAD

**Issue by leggebroten** [marcdel/open_telemetry_decorator#113]
For event driven architectures, many spans do not have a parent-child relationship but rather a "causal" relationship.
OpenTelemetry supports this functionality by adding one or more [Links](https://opentelemetry.io/docs/instrumentation/erlang/manual/#linking-the-new-span) when creating the new span

A good [blog from Lightstep](https://lightstep.com/blog/using-span-links-in-lightstep) discusses the issue.

I would like to submit a PR supporting this capability perhaps as a new `links:` option (sibling to the current `include:` option).

The value passed to the `links:` option would be a "path" specification exactly analogous to that given to `include:`

## Example
Traced function being invoked as an event with a `causal_link` field containing the OTLP link to the originating span
```elixir
      @decorate trace("Example.with.link", include: [:msg], links: [[:msg, :causal_link]])
      def link(msg), do: {:ok, msg}
```

Alternatively, a user could use pattern matching to make the `links` list easier to grok
```elixir
      @decorate trace("Example.with.link", include: [:msg], links: [:causal_link])
      def link(%{causal_link: causal_link}), do: {:ok, msg}
```

Example test showing how the causal link is created, passed to the traced function, and added to the created span
```elixir

    test "when `link` option present, the traced span will have the specified OTLP Link" do
      # Simulate a trace that has completed
      causal_span = Tracer.start_span("causal-span")
      span_ctx(span_id: causal_span_id) = Span.end_span(causal_span)

      # Create a link to that other trace
      link_to_causal_span = OpenTelemetry.link(causal_span)

      # Simulate receiving a message containing a link to a causal span
      Example.link(%{causal_link: link_to_causal_span})

      # Validate that the "traced" span was created with the link
      assert_receive {:span, span(name: "Example.with.link", links: links)}

      [link] = get_span_links(links)

      link(span_id: ^causal_span_id) = link
    end
```

**Comment by benregn** [comment]
@marcdel have you had any time to think about this? I came over to write basically the exact same request 😁 I'm having the same pain with events sent over Phoenix PubSub.

**Comment by marcdel** [comment]
Added in [v1.4.9](https://github.com/marcdel/open_telemetry_decorator/releases/tag/v1.4.9)

**Comment by benregn** [comment]
@marcdel Is it possible to do `links: [[:opts, :otel_link_span]]` like with `includes`? Look at the code a bit but didn't dig in so I'm not sure.
