### ISSUE TITLE
Make call to set_attributes to match the OTLP specs

### ISSUE THREAD

**Issue by leggebroten** [marcdel/open_telemetry_decorator#114]
Currently, the result of `Attributes.get_attributes` returns a Keyword which is then passed directly to `Tracer.set_attributes`.  

This is not consistent with the [spec](https://hexdocs.pm/opentelemetry_api/OpenTelemetry.html#t:attributes_map/0) which expects a list of two element tuples, {attribute_name_as_binary, OTLP_acceptable_value}

Where a OTLP_acceptable_value is: string, integer, double or boolean

This could lead to integration issues with certain providers.

## Example
```elixir
[{"/http/user_agent" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"}
 {"/http/server_latency", 300}
 {"abc.com/myattribute", True}
 {"abc.com/score", 10.239}]
```

**Comment by marcdel** [comment]
Good catch! Fixed in 2f5ac96883437f485e667ea7682b8faa91b565a0
