### ISSUE TITLE
Feature request: Support prefixing span attributes

### ISSUE THREAD

**Issue by benregn** [marcdel/open_telemetry_decorator#38]
I have a feature request: Would it be possible to globally define a prefix for all span attributes specified in the `include` option?

Thanks for working on this library!

**Comment by marcdel** [comment]
Sorry this is super super late, @benregn but would you mind saying more about your use case?

**Comment by benregn** [comment]
Sure. It's mostly a desire to provide a namespace for the attributes I explicitly add to spans, e.g. `app.`. It's also a practice in the semantic conventions in the official spec like `db.` for everything database related or `http.` for all HTTP related. It's also mentioned in Honeycomb's docs https://docs.honeycomb.io/getting-data-in/data-best-practices/#namespace-custom-fields. As an added benefit, it groups all your "custom" attributes together in the list of attributes for a span (at least in Honeycomb).

**Comment by marcdel** [comment]
Ahh, yeah that makes sense!

**Comment by marcdel** [comment]
Fixed in #92, hex version `1.2.3`
